---
title: "Data QCQA" 
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'BB2_data_QCQA.html')) })
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---
<!-- NOTES: 
1) Make sure to update file name in knit above (e.g., BB2_data_QCQA.html) 
2) Update init file below (e.g., BB2_data_QCQA.R) -->

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(ggplot2)
library(knitr)
```

```{r echo=FALSE}
# Comments/Notes
# 1) Make variables generalizable for different variable names - USE AMERIFLUX NAMES HERE (make sure to update plots below) - make scatterplot generalizable - Temperature scatterplot could be more generalizable
# 2) NEED TO ADD 7200, 7700 temp and 7200 RH & CHECK WHICH TEMP IS USED TO SONIC (cross wind corrected or no) ADD HERE after MEETING ON THURSDAY!
# 3) Try to track down WD_CUP at all sites
# 4) Remove duplicate variables (e.g., see google sheets for tracking)
# 5) Think about output directory (can change by replacing 'dirname(inputFile)' above)
```

<!-- specify init file to read -->
```{r echo=FALSE}
read_chunk('init_files/BB2_data_QCQA.R')
```

```{r, echo=FALSE}
<<LoadData>>
```

Sonic data 
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Sonic variables and diagnostics

```{r}
# Load all plotting functions
sonic_plots(data,vars_WS,vars_WD,vars_other_sonic,units_other_sonic,pitch_ind)
```

Column {data-width=400}
-----------------------------------------------------------------------

### mean wind speed vs. u*
```{r}
scatter_plot_QCQA(data,eval(parse(text = paste0("data$",vars_WS[1]))),
                  sqrt(eval(parse(text = paste0("data$",vars_other_sonic[1])))),
                  year,"WD (m/s)","USTAR (m/s)")
```

### sigma_w vs. u*
```{r}
scatter_plot_QCQA(data,eval(parse(text = paste0("data$",vars_other_sonic[1]))),
                  sqrt(eval(parse(text = paste0("data$",wind_variance[1])))),
                  year,"USTAR (m/s)","W_SIGMA (m/s")
```

Temperature data 
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Air and RH temperature comparison 
```{r}
temp_RH_plots(data,vars_temp,vars_RH)
```

Column {data-width=400}
-----------------------------------------------------------------------

### Temperature scatterplot
```{r}
scatter_plot_temp_QCQA(data,eval(parse(text = paste0("data$",vars_temp[1]))),
                       eval(parse(text = paste0("data$",vars_temp[2]))),
                       eval(parse(text = paste0("data$",vars_temp[3]))),
                       c("Sonic","7700"),
                       "HMP Air temperature (°C)","Other Air Temperature (°C)")
```

### RH HMP vs. RH 7200

```{r}
scatter_plot_QCQA(data,eval(parse(text = paste0("data$",vars_RH[1]))),
                  eval(parse(text = paste0("data$",vars_RH[2]))),year,
                  "HMP RH (%)","LI-7200 RH (%)")
```


Radiation data  
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Radiation timeseries  
```{r}
radiation_plots(data,vars_radiometer,vars_NETRAD,vars_PPFD)
```

Column {data-width=400}
-----------------------------------------------------------------------

### SW_IN vs PPDF_IN
```{r}
scatter_plot_QCQA(data,eval(parse(text = paste0("data$",vars_radiometer[1]))),
                  eval(parse(text = paste0("data$",vars_PPFD[1]))),
                  year,"SW_IN (W/m2)","PPFD_IN (µmolPhoton/m2/s1)")
```

### SW_OUT vs PPFD_OUT

```{r}
scatter_plot_QCQA(data,eval(parse(text = paste0("data$",vars_radiometer[2]))),
                  eval(parse(text = paste0("data$",vars_PPFD[2]))),
                  year,"SW_OUT (W/m2)","PPFD_OUT (µmolPhoton/m2/s1)")
```

Barometric pressure and other variables   
=======================================================================

Column {data-width=600}
-----------------------------------------------------------------------

### Atmospheric pressure and precipitation  
```{r}
# Barometric pressure 
plotly_loop(data,vars_pressure)%>%
  layout(yaxis = list(title = "Barometric pressure (units)"))%>%
  toWebGL()
```

Column {data-width=400}
-----------------------------------------------------------------------

### SW_IN vs PPDF_IN
```{r}

```

### SW_OUT vs PPFD_IN
```{r}

```


