---
title: "DSM_data_secondstage"
author: "Sara Knox"
output: html_document
---
<!-- NOTES: 
Need an excel spreadsheet similar to 'name_mapping_DSM.xlsx' to run -->

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(dplyr)
library(plotly)
library(ggplot2)
library(knitr)
library(htmltools)
knitr::opts_chunk$set(echo = TRUE)
opts_knit$set(root.dir = "/Users/sara/Code/MLABcode/data_visualization") # Specify directory

# Ideas for improvement
# 1) Units for ylabel
# 3) Interactive plots (especially for fluxes)
```

# Plot second stage data {.tabset}

here you can visualize all the variables from second stage data cleaning and assess any potential issues. Note that variable in light gray is the stage one data and the blue dots is the stage two data.

## Met
```{r create plots met,echo=FALSE,warning=FALSE,message=FALSE,results='hide',fig.show='hide'}
# This is our external R script for a quick visualization of the first stage data
# Could make fancier with shiny
basepath <- "/Users/sara/Library/CloudStorage/OneDrive-UBC/UBC/database"

yrs <- c(2021,2022)
site <- "DSM"
level <- c("Met")

# Specify path for working directories from which to read variables
wd_stagethree <- paste0(basepath,"/",yrs[1],"/",site,"/clean/ThirdStage",sep = "")
wd_stageone <- paste0(basepath,"/",yrs[1],"/",site,"/",level,"/clean",sep = "")

# List all files in 'StageThree' and from stage one folder
# Generalize to loop through years
vars_stagethree <-  list.files(paste0(basepath,"/",yrs[1],"/",site,"/clean/ThirdStage",sep = ""))
vars_stageone <-  list.files(paste0(basepath,"/",yrs[1],"/",site,"/",level,"/clean",sep = ""))

k <- 0
colors <- c("stage one" = "lightgray", "stage three" = "steelblue")
plots <- plot.new()

for (j in 1:(length(vars_stagethree))) { 
  l <- list()
  for (i in 1:length(yrs)) { 
    
    # Specify path for working directories from which to read variables
    wd_stagethree <- paste0(basepath,"/",yrs[i],"/",site,"/clean/ThirdStage",sep = "")
    wd_stageone <- paste0(basepath,"/",yrs[i],"/",site,"/",level,"/clean",sep = "")
    
    # Define time vector for plotting
    setwd(wd_stagethree)
    tv <- readBin("clean_tv",double(),n = 18000)
    datetime <- as.POSIXct((tv - 719529)*86400, origin = "1970-01-01", tz = "UTC")
    # Round to nearest 30 min
    datetime <- lubridate::round_date(datetime, "30 minutes") 
    
    # Load stagethree trace
    var_stagethree_name <- vars_stagethree[j]
    
    # Skip tv varibles
    if (var_stagethree_name == "clean_tv") next
    
    setwd(wd_stagethree)
    var_stagethree <- readBin(var_stagethree_name,numeric(),n = 18000,size = 4)
    
    # Replace NaN with NA
    ind <- is.nan(var_stagethree) 
    var_stagethree[ind] <- NA
    
    # Load original trace
    ind <- which(vars_stageone == var_stagethree_name)
    
    # skip variable if it's not in stage one
    if (length(ind) == 0) next
    
    var_stageone_name <- vars_stageone[ind]
    #var_orig_name <- paste0("var_name_mapping$Orig_db_name_",level[i],sep = "")[ind]
    
    print(paste0('stage one name = ',var_stageone_name, ' | stage three name = ',var_stagethree_name ,sep = ''))
    
    setwd(wd_stageone) # If getting error 'cannot change working directory', make sure you are connected to vinimet
    var_stageone <- readBin(var_stageone_name,numeric(),n = 18000,size = 4)
    
    # Replace NaN with NA
    ind <- is.nan(var_stageone) 
    var_stageone[ind] <- NA
    
    df.now <- data.frame(datetime, var_stagethree,var_stageone)
    l[[i]] <- df.now
    
  }
  
  if (var_stagethree_name == "clean_tv") next
  if (length(ind) == 0) next
  
  k <- k+1
  print(k)
  
  df <- do.call(rbind,l)
  
  p <- ggplot() + 
    geom_point(data = df, aes(x = datetime, y = var_stageone, color = "stage one")) +
    geom_point(data = df, aes(x = datetime, y = var_stagethree, color = "stage three")) +
    ylab(var_stagethree_name) +  xlab("Date") +
    scale_color_manual(values = colors)+
    theme(legend.position="top",
          legend.title=element_blank())
  
  plots[[k]] <- p
  graphics.off()
}
```

```{r plot variables met,echo=FALSE,warning=FALSE,message=FALSE,results='hide',fig.keep='all'}
plots
```

## Flux
```{r create plots flux,echo=FALSE,warning=FALSE,message=FALSE,results='hide',fig.show='hide'}
# This is our external R script for a quick visualization of the second stage data
# Could make fancier with shiny

basepath <- "/Users/sara/Library/CloudStorage/OneDrive-UBC/UBC/database"
yrs <- c(2021,2022)
site <- "DSM"
level <- c("Flux")

# List all files in met 'StageOne' 
vars_stageone_met <-  list.files(paste0(basepath,"/",yrs[1],"/",site,"/","Met","/clean",sep = ""))

# Specify path for working directories from which to read variables
wd_stagethree <- paste0(basepath,"/",yrs[1],"/",site,"/clean/ThirdStage",sep = "")
wd_stageone <- paste0(basepath,"/",yrs[1],"/",site,"/",level,"/clean",sep = "")

# List all files in 'StageThree' and from stage one folder
vars_stagethree <-  list.files(paste0(basepath,"/",yrs[1],"/",site,"/clean/ThirdStage",sep = ""))
vars_stageone <-  list.files(paste0(basepath,"/",yrs[1],"/",site,"/",level,"/clean",sep = ""))

k <- 0
colors <- c("stage one" = "lightgray", "stage three" = "steelblue")
plots <- plot.new()

for (j in 1:(length(vars_stagethree))) { 
  l <- list()
  for (i in 1:length(yrs)) { 
    
    wd_stagethree <- paste0(basepath,"/",yrs[i],"/",site,"/clean/ThirdStage",sep = "")
    wd_stageone <- paste0(basepath,"/",yrs[i],"/",site,"/",level,"/clean",sep = "")
    
    # Define time vector for plotting
    setwd(wd_stagethree)
    tv <- readBin("clean_tv",double(),n = 18000)
    datetime <- as.POSIXct((tv - 719529)*86400, origin = "1970-01-01", tz = "UTC")
    # Round to nearest 30 min
    datetime <- lubridate::round_date(datetime, "30 minutes") 
    
    # Load stage two trace
    var_stagethree_name <- vars_stagethree[j]
    
    # Skip tv variables
    if (var_stagethree_name == "clean_tv") next
    
    setwd(wd_stagethree)
    var_stagethree <- readBin(var_stagethree_name,numeric(),n = 18000,size = 4)
    
    # Replace NaN with NA
    ind <- is.nan(var_stagethree) 
    var_stagethree[ind] <- NA
    
    # Load original trace
    ind <- which(vars_stageone == var_stagethree_name)
    
    # plot only stage three data if stage one data isn't available (and the variable is a flux variable), else plot stage one and stage two data
    if (length(ind) == 0 & length(which(vars_stageone_met == var_stagethree_name)) == 0) {
      
      df.now <- data.frame(datetime, var_stagethree)
      l[[i]] <- df.now
      
      print(paste0('stage three only = ',var_stagethree_name ,sep = ''))
      
    } else if (length(ind) != 0)  {
      
      var_stageone_name <- vars_stageone[ind]
      #var_orig_name <- paste0("var_name_mapping$Orig_db_name_",level[i],sep = "")[ind]
      
      print(paste0('stage one name = ',var_stageone_name, ' | stage three name = ',var_stagethree_name ,sep = ''))
      
      setwd(wd_stageone) # If getting error 'cannot change working directory', make sure you are connected to vinimet
      var_stageone <- readBin(var_stageone_name,numeric(),n = 18000,size = 4)
      
      # Replace NaN with NA
      ind <- is.nan(var_stageone) 
      var_stageone[ind] <- NA
      
      df.now <- data.frame(datetime, var_stagethree,var_stageone)
      l[[i]] <- df.now
    }
  }
  
  if (var_stagethree_name == "clean_tv") next
  
  if (length(ind) == 0 & length(which(vars_stageone_met == var_stagethree_name)) == 0) {
    
    k <- k+1
    print(k)
    
    df <- do.call(rbind,l)
    p <- ggplot() + 
      geom_point(data = df, aes(x = datetime, y = var_stagethree)) +
      ylab(var_stagethree_name) +  xlab("Date") 
    
    plots[[j]] <- p
    graphics.off()
    
  } else if (length(ind) != 0)  {
    
    
    k <- k+1
    print(k)
    
    df <- do.call(rbind,l) 
    
    p <- ggplot() + 
      geom_point(data = df, aes(x = datetime, y = var_stageone, color = "stage one")) +
      geom_point(data = df, aes(x = datetime, y = var_stagethree, color = "stage three")) +
      ylab(var_stagethree_name) +  xlab("Date") +
      scale_color_manual(values = colors)+
      theme(legend.position="top",
            legend.title=element_blank())
    
    plots[[j]] <- p
    graphics.off()
  }
}
```

```{r plot variables flux,echo=FALSE,warning=FALSE,message=FALSE,results='hide',fig.keep='all'}
plots
```