---
title: "MLABcode documentation"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<!--Think about if I want this here or in README.md-->

This document provides information and details on how to process eddy covariance and biomet data from start to finish.

## High frequency data processing 

## Post-processing 30 min data

### L1

### L2

### L3

## Data visualization 

Prior to using the data for analyses or submitting data to AmeriFlux, use the script `dashboard_data_QCQA.Rmd` to visualize post-processed eddy covariance and biomet data for one final check.

`dashboard_data_QCQA.Rmd` is found under `MLABcode` > `data_visualization`.

### Instructions
1) Prior to running `dashboard_data_QCQA.Rmd`, make sure to create or update the init file for each site (under `init_files` folder).    
2) Prior to running `dashboard_data_QCQA.Rmd`, make sure to update the output file name on _line 3_ (e.g., `BB2_data_QCQA.html`) **and** the name of the init file on _line 31_ (e.g., `BB2_data_QCQA.R`).    
3) Now inspect each variable to assess if variable needs further attention. 

the end
